site_name: 懂色av- -海量作品任你选的网站入口
site_author: 懂色av
site_description: 懂色av是国内专业的正版漫画阅读平台，提供海量高清中日韩漫画资源，支持多端同步阅读与创作者扶持计划。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
